import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { CsdGeneratedModule, CsdGeneratedSharedModule } from './generated/module';
import { CsdValidator, registerValidationChecks } from './csd-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type CsdAddedServices = {
    validation: {
        CsdValidator: CsdValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type CsdServices = LangiumServices & CsdAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const CsdModule: Module<CsdServices, PartialLangiumServices & CsdAddedServices> = {
    validation: {
        CsdValidator: () => new CsdValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createCsdServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Csd: CsdServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        CsdGeneratedSharedModule
    );
    const Csd = inject(
        createDefaultModule({ shared }),
        CsdGeneratedModule,
        CsdModule
    );
    shared.ServiceRegistry.register(Csd);
    registerValidationChecks(Csd);
    return { shared, Csd };
}
