version: "3.8"

services:
  apollo-server:
    build:
      context: ./csd-graphql
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Expose Apollo server's port
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./csd-graphql
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
    networks:
      - backend
      - frontend

  nextjs-frontend:
    build:
      context: ./csd-frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000" # Expose Next.js's port
    depends_on:
      - apollo-server # Ensure Apollo server starts first
    volumes:
      - type: bind
        source: ./csd-frontend
        target: /usr/src/app
      - type: volume
        target: /usr/src/app/node_modules
      - type: volume
        target: /usr/src/app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true

    networks:
      - frontend

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
  frontend:
