
version: '3.8'

services:
  apollo-server:
    build:
      context: ./csd-graphql
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # Expose Apollo server's port
    depends_on:
      - db
    volumes:
      - ./csd-graphql:/app
    networks:
      - backend
      - frontend

  nextjs-frontend:
    build:
      context: ./csd-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose Next.js's port
    depends_on:
      - apollo-server # Ensure Apollo server starts first
    volumes:
      - ./csd-frontend:/app
    networks:
      - frontend
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
