export enum UserRole {
  DEVELOPER = 'DEVELOPER',

  ARCHITECT = 'ARCHITECT',

  SECURITYEXPERT = 'SECURITYEXPERT',

  SYSADMINISTRATOR = 'SYSADMINISTRATOR',

  MANAGER = 'MANAGER',

  OTHER = 'OTHER',
}
